# sample configuration file for config entirely from remote service. When retrieving from remote,
# will also be told how to handle telemetry.
# can be overridden by command-line arguments

# standard reference of type and version
version: config.databack.io/v1
kind: remote

# receives the config from the config service, so nothing else needed 
spec:
  url: https://config.databack.io
  # sha256 fingerprint of certificates for the server, or one or more of the certificates in the signing chain; unneeded if the server is using a certificate signed by a well-known CA
  # this is a sample fingerprint only
  # DO NOT USE THIS FINGERPRINT; GET THE ACTUAL ONE FROM YOUR REMOTE SERVER!
  certificates: sha256:69729b8e15a86efc177a57afb7171dfc64add28c2fca8cf1507e34453ccb1470
  # base64-encoded Curve25519 private key for authentication to the server, as well as decrypting the provided configuration
  # this is a sample key only
  # DO NOT USE THIS KEY; GENERATE YOUR OWN!
  credentials: BwMqVfr1myxqX8tikIPYCyNtpHgMLIg/2nUE+pLQnTE=
